name: Nightly Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit hash to build"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle

      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: List built APK files
        run: ls -la app/build/outputs/apk/release/

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk EasyNotes-nightly.apk

      - name: Upload the APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: EasyNotes-Nightly
          path: EasyNotes-nightly.apk

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: Nightly
          token: ${{ secrets.TOKEN }}
          files: EasyNotes-nightly.apk
